name: watchlist
description: Search and keep track of your favorite movies.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  touch_indicator: ^1.0.2
  state_persistence: ^0.0.6
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  json_annotation: ^3.0.0
  recase: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  build_runner: ^1.6.7
  json_serializable: ^3.2.2

flutter:
  uses-material-design: true
